// Code generated by schemagen; DO NOT EDIT.
// Edit the struct and rerun: go generate ./...

package catalog

import (
	"time"

	"github.com/mbauer83/effect-golang-web/schema"
)

// CatalogSchema describes Catalog. It is generated from the struct.
var CatalogSchema = schema.Documented("Catalog is what one document holds.",
	schema.Struct[Catalog]("Catalog",
		schema.DocumentedField("Name identifies the catalogue.",
			schema.FieldOf("name", schema.Text(),
				func(value Catalog) string { return value.Name },
				func(value *Catalog, field string) { value.Name = field })),
		schema.DocumentedField("Books are every entry, in the order the catalogue lists them.",
			schema.FieldOf("books", schema.List(BookSchema),
				func(value Catalog) []Book { return value.Books },
				func(value *Catalog, field []Book) { value.Books = field })),
	))

// BookSchema describes Book. It is generated from the struct.
var BookSchema = schema.Documented("Book is one entry.",
	schema.Struct[Book]("Book",
		schema.DocumentedField("Title is what the book is called.",
			schema.FieldOf("title", schema.Text(),
				func(value Book) string { return value.Title },
				func(value *Book, field string) { value.Title = field })),
		schema.DocumentedField("Authors are credited in the order the book credits them.",
			schema.FieldOf("authors", schema.List(schema.Text()),
				func(value Book) []string { return value.Authors },
				func(value *Book, field []string) { value.Authors = field })),
		schema.DocumentedField("Pages is how many pages the book has, and there is at least one.",
			schema.FieldOf("pages", pagesSchema,
				func(value Book) int { return value.Pages },
				func(value *Book, field int) { value.Pages = field })),
		schema.DocumentedField("Subtitle is absent for a book that has none.",
			schema.OptionalFieldOf("subtitle", schema.Text(),
				func(value Book) (string, bool) {
					var absent string
					if value.Subtitle == nil {
						return absent, false
					}
					return *value.Subtitle, true
				},
				func(value *Book, field string) { value.Subtitle = &field })),
		schema.DocumentedField("Availability is whether the book can be had.",
			schema.FieldOf("availability", AvailabilitySchema,
				func(value Book) Availability { return value.Availability },
				func(value *Book, field Availability) { value.Availability = field })),
	))

// InStockSchema describes InStock. It is generated from the struct.
var InStockSchema = schema.Documented("InStock is a title on the shelf, with how many copies.",
	schema.Struct[InStock]("InStock",
		schema.DocumentedField("Count is how many copies are on the shelf.",
			schema.FieldOf("count", schema.Int(),
				func(value InStock) int { return value.Count },
				func(value *InStock, field int) { value.Count = field })),
	))

// AwaitedSchema describes Awaited. It is generated from the struct.
var AwaitedSchema = schema.Documented("Awaited is a title not yet arrived, with when it is expected.",
	schema.Struct[Awaited]("Awaited",
		schema.DocumentedField("Expected is when the title should arrive.",
			schema.FieldOf("expected", schema.Time(),
				func(value Awaited) time.Time { return value.Expected },
				func(value *Awaited, field time.Time) { value.Expected = field })),
	))

// DiscontinuedSchema describes Discontinued. It is generated from the struct.
var DiscontinuedSchema = schema.Documented("Discontinued is a title that will not be restocked.",
	schema.Struct[Discontinued]("Discontinued"))
