package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// render writes the package's schemas.
//
// It emits the same combinator calls a hand-written schema uses, so a generated
// schema and a written one stay interchangeable and a reader has one thing to
// learn rather than two.
func render(collected collected) ([]byte, error) {
	var written bytes.Buffer
	fmt.Fprintf(&written, "// Code generated by schemagen; DO NOT EDIT.\n")
	fmt.Fprintf(&written, "// Edit the struct and rerun: go generate ./...\n\n")
	fmt.Fprintf(&written, "package %s\n\n", collected.packageName)
	renderImports(&written, collected)

	for _, described := range collected.types {
		if err := renderType(&written, described, "the struct"); err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source(written.Bytes())
	if err != nil {
		return nil, fmt.Errorf("the generated source does not parse: %w\n%s", err, written.String())
	}
	return formatted, nil
}

const schemaPackage = "github.com/mbauer83/effect-golang-web/schema"

// renderImports imports the schema package and whatever the accessors name.
// An accessor returns the field's own type, so a field of type time.Time makes
// the generated file need time -- and the source file already says what that
// qualifier stands for.
func renderImports(written *bytes.Buffer, collected collected) {
	standard := []string{}
	elsewhere := []string{schemaPackage}
	for _, qualifier := range qualifiersIn(collected.types) {
		path, known := collected.imports[qualifier]
		switch {
		case !known:
			continue
		case strings.Contains(strings.SplitN(path, "/", 2)[0], "."):
			elsewhere = append(elsewhere, path)
		default:
			standard = append(standard, path)
		}
	}
	sort.Strings(standard)
	sort.Strings(elsewhere)

	// Grouped as a person would write them: the standard library, then
	// everything else. Generated code that does not look like written code
	// invites being reformatted, and then it drifts.
	fmt.Fprintf(written, "import (\n")
	for _, path := range standard {
		fmt.Fprintf(written, "%q\n", path)
	}
	if len(standard) > 0 {
		fmt.Fprintf(written, "\n")
	}
	for _, path := range elsewhere {
		fmt.Fprintf(written, "%q\n", path)
	}
	fmt.Fprintf(written, ")\n")
}

// qualifier finds a package qualifier in a rendered type.
var qualifier = regexp.MustCompile(`\b([a-z][A-Za-z0-9_]*)\.`)

// qualifiersIn returns the qualifiers used, in no particular order: the paths
// they resolve to are sorted where that matters, which is in the import block.
func qualifiersIn(types []structType) []string {
	found := map[string]bool{}
	for _, described := range types {
		for _, field := range described.fields {
			for _, match := range qualifier.FindAllStringSubmatch(field.goType+" "+field.element, -1) {
				found[match[1]] = true
			}
		}
	}
	names := make([]string, 0, len(found))
	for name := range found {
		names = append(names, name)
	}
	return names
}

// renderType writes one schema. A struct with no fields is allowed: an empty
// variant of a union is a real shape, and refusing it would make one
// unexpressible.
func renderType(written *bytes.Buffer, described structType, origin string) error {
	fmt.Fprintf(written, "\n// %sSchema describes %s. It is generated from %s.\n",
		described.name, described.name, origin)
	fmt.Fprintf(written, "var %sSchema = ", described.name)
	if described.doc != "" {
		fmt.Fprintf(written, "schema.Documented(%s,\n", strconv.Quote(described.doc))
	}
	fmt.Fprintf(written, "schema.Struct[%s](%s,\n", described.name, strconv.Quote(described.name))
	for _, field := range described.fields {
		renderField(written, described.name, field)
	}
	fmt.Fprintf(written, ")")
	if described.doc != "" {
		fmt.Fprintf(written, ")")
	}
	fmt.Fprintf(written, "\n")
	return nil
}

func renderField(written *bytes.Buffer, owner string, field structField) {
	if field.doc != "" {
		fmt.Fprintf(written, "schema.DocumentedField(%s,\n", strconv.Quote(field.doc))
	}
	if field.optional {
		renderOptional(written, owner, field)
	} else {
		renderRequired(written, owner, field)
	}
	if field.doc != "" {
		fmt.Fprintf(written, ")")
	}
	fmt.Fprintf(written, ",\n")
}

func renderRequired(written *bytes.Buffer, owner string, field structField) {
	fmt.Fprintf(written, "schema.FieldOf(%s, %s,\n", strconv.Quote(field.wire), field.shape)
	fmt.Fprintf(written, "func(value %s) %s { return value.%s },\n",
		owner, field.goType, field.name)
	fmt.Fprintf(written, "func(value *%s, field %s) { value.%s = field })",
		owner, field.goType, field.name)
}

// renderOptional reads presence from the pointer, which is the only honest
// answer: a zero value is not absence, and the schema deliberately refuses to
// guess that it is.
func renderOptional(written *bytes.Buffer, owner string, field structField) {
	fmt.Fprintf(written, "schema.OptionalFieldOf(%s, %s,\n", strconv.Quote(field.wire), field.shape)
	fmt.Fprintf(written, "func(value %s) (%s, bool) {\n", owner, field.element)
	fmt.Fprintf(written, "var absent %s\n", field.element)
	fmt.Fprintf(written, "if value.%s == nil { return absent, false }\n", field.name)
	fmt.Fprintf(written, "return *value.%s, true\n},\n", field.name)
	fmt.Fprintf(written, "func(value *%s, field %s) { value.%s = &field })",
		owner, field.element, field.name)
}
