// Code generated by schemagen; DO NOT EDIT.
// Edit the struct and rerun: go generate ./...

package bookstore

import (
	"github.com/mbauer83/effect-golang-web/schema"
)

// BookSchema describes Book. It is generated from the struct.
var BookSchema = schema.Documented("Book is one entry.",
	schema.Struct[Book]("Book",
		schema.DocumentedField("Title is what the book is called.",
			schema.FieldOf("title", schema.MaxLength(schema.MinLength(schema.Text(), 1), 200),
				func(value Book) string { return value.Title },
				func(value *Book, field string) { value.Title = field })),
		schema.DocumentedField("Authors are credited in the order the book credits them.",
			schema.FieldOf("authors", schema.MaxItems(schema.List(schema.Text()), 64),
				func(value Book) []string { return value.Authors },
				func(value *Book, field []string) { value.Authors = field })),
		schema.DocumentedField("Pages is how many pages the book has, and there is at least one.",
			schema.FieldOf("pages", schema.AtMost(schema.AtLeast(schema.Int(), 1), 20000),
				func(value Book) int { return value.Pages },
				func(value *Book, field int) { value.Pages = field })),
	))
