// Code generated by schemagen; DO NOT EDIT.
// Edit the struct and rerun: go generate ./...

package bookstore

import (
	"github.com/mbauer83/effect-golang-web/schema"
)

// BookSchema describes Book. It is generated from the struct.
var BookSchema = schema.Documented("Book is one entry.",
	schema.Struct[Book]("Book",
		schema.FieldOf("title", schema.Text(),
			func(value Book) string { return value.Title },
			func(value *Book, field string) { value.Title = field }),
		schema.FieldOf("authors", schema.List(schema.Text()),
			func(value Book) []string { return value.Authors },
			func(value *Book, field []string) { value.Authors = field }),
		schema.DocumentedField("Pages is how many pages the book has, and there is at least one.",
			schema.FieldOf("pages", pagesSchema,
				func(value Book) int { return value.Pages },
				func(value *Book, field int) { value.Pages = field })),
	))
