// Package warehouse keeps pallets, and its tables come from its description.
//
// One description does four jobs here. It decodes and encodes the wire; it
// derives what a caller supplies to create a pallet and what a caller supplies
// to change one; and it says which tables hold it. So a column that changed
// would change all four together, which is the whole reason there is one
// description rather than four.
//
// A pallet is an aggregate, not a row. The items on it are entities -- they have
// identities of their own -- so they get a table of their own and a reference
// back. The warehouse a pallet sits in is a plain value and lives in the
// pallet's row.
package warehouse

import (
	"time"

	"github.com/mbauer83/effect-golang-web/schema"
	"github.com/mbauer83/effect-golang-web/schema/dynamic"
)

// Item is one thing on a pallet. It has an identity, so it is a thing rather
// than a part.
type Item struct {
	ID       string
	SKU      string
	Quantity int32
}

// ItemSchema describes an item.
//
// The identity is the application's -- a UUID it generates -- so it is Identity
// without Computed, and a caller creating a pallet supplies it. That is the
// distinction Identity and Computed compose to make.
var ItemSchema = schema.Struct[Item]("PalletItem",
	schema.FieldOf("id", schema.MaxLength(schema.UUID(), 36),
		func(held Item) string { return held.ID },
		func(held *Item, value string) { held.ID = value }).
		Identity().
		Documented("ID is the item's own, generated by whoever puts it on the pallet."),
	schema.FieldOf("sku", schema.MinLength(schema.Text(), 1),
		func(held Item) string { return held.SKU },
		func(held *Item, value string) { held.SKU = value }),
	schema.FieldOf("quantity", schema.AtLeast(schema.Int32(), 1),
		func(held Item) int32 { return held.Quantity },
		func(held *Item, value int32) { held.Quantity = value }),
).Documented("PalletItem is one line of what a pallet holds.")

// Pallet is the aggregate root.
type Pallet struct {
	ID        int64
	Reference string
	Warehouse string
	Items     []Item
	StoredAt  time.Time
}

// PalletSchema describes a pallet.
//
// The identity is the database's, so it is Identity and Computed together and a
// caller creating a pallet does not supply it. StoredAt is Computed with a
// default, which is the other half a projection to storage needs: Computed says
// the value is not the caller's, and the default says what produces it.
var PalletSchema = schema.Struct[Pallet]("Pallet",
	schema.FieldOf("id", schema.Int64(),
		func(held Pallet) int64 { return held.ID },
		func(held *Pallet, value int64) { held.ID = value }).
		Identity().
		Computed().
		Documented("ID is assigned when the pallet is first stored."),
	schema.FieldOf("reference", schema.MaxLength(schema.MinLength(schema.Text(), 1), 32),
		func(held Pallet) string { return held.Reference },
		func(held *Pallet, value string) { held.Reference = value }).
		Documented("Reference is what the label says."),
	schema.FieldOf("warehouse", schema.MinLength(schema.Text(), 1),
		func(held Pallet) string { return held.Warehouse },
		func(held *Pallet, value string) { held.Warehouse = value }).
		Documented("Warehouse is where it sits. A plain value, so it lives in this row."),
	schema.FieldOf("items", schema.List(ItemSchema),
		func(held Pallet) []Item { return held.Items },
		func(held *Pallet, value []Item) { held.Items = value }).
		Documented("Items are entities, so they get a table of their own."),
	schema.FieldOf("storedAt", schema.Time(),
		func(held Pallet) time.Time { return held.StoredAt },
		func(held *Pallet, value time.Time) { held.StoredAt = value }).
		Computed().
		DefaultingToNow().
		Documented("StoredAt is when it arrived, which the database records."),
).Documented("Pallet is a pallet in a warehouse, with what is on it.")

// Stored is what a database hands back about a pallet it has just taken: the
// key it assigned, and whether the moment it records was recorded.
//
// Not the instant itself, because how a timestamp comes back is the driver's
// business and differs -- one hands back an instant and another the text it
// stored. What the description claims is that the column has a value without
// anybody supplying one, and that is what this asks.
type Stored struct {
	ID    int64
	Dated int64
}

// StoredSchema reads the key and whether the default applied.
var StoredSchema = schema.Struct[Stored]("Stored",
	schema.FieldOf("id", schema.Int64(),
		func(held Stored) int64 { return held.ID },
		func(held *Stored, value int64) { held.ID = value }),
	// An integer and not a boolean, because a driver spells a truth value in
	// whatever its database has: SQLite has no boolean and hands back nought
	// or one, which is exactly what this module's own SQLite dialect says when
	// it maps a boolean column to an integer.
	schema.FieldOf("dated", schema.Int64(),
		func(held Stored) int64 { return held.Dated },
		func(held *Stored, value int64) { held.Dated = value }),
)

// Counted is one number a query returned.
type Counted struct {
	Count int64
}

// CountedSchema reads it.
var CountedSchema = schema.Struct[Counted]("Counted",
	schema.FieldOf("count", schema.Int64(),
		func(held Counted) int64 { return held.Count },
		func(held *Counted, value int64) { held.Count = value }),
)

// Text is a value bound as a statement's argument, so a test and a program
// spell it the same way.
func Text(value string) dynamic.Value {
	return dynamic.OfText(value)
}
