// Code generated by schemagen; DO NOT EDIT.
// Edit the description and rerun: go generate ./...

package inventory

import "github.com/mbauer83/effect-golang-web/schema"

// Item is generated from its description.
type Item struct {
	// the stock-keeping unit, three letters and five digits
	Sku string `json:"sku"`
	// how many are on hand
	OnHand uint16 `json:"onHand"`
	// what one unit weighs
	WeightGrams float32  `json:"weightGrams"`
	ID          string   `json:"id"`
	Tags        []string `json:"tags"`
	Note        *string  `json:"note,omitempty"`
}

// ItemSchema describes Item. It is generated from its description.
var ItemSchema = schema.Struct[Item]("Item",
	schema.DocumentedField("the stock-keeping unit, three letters and five digits",
		schema.FieldOf("sku", schema.Matching(schema.Text(), "^[A-Z]{3}-[0-9]{5}$"),
			func(value Item) string { return value.Sku },
			func(value *Item, field string) { value.Sku = field })),
	schema.DocumentedField("how many are on hand",
		schema.FieldOf("onHand", schema.Uint16(),
			func(value Item) uint16 { return value.OnHand },
			func(value *Item, field uint16) { value.OnHand = field })),
	schema.DocumentedField("what one unit weighs",
		schema.FieldOf("weightGrams", schema.Float32(),
			func(value Item) float32 { return value.WeightGrams },
			func(value *Item, field float32) { value.WeightGrams = field })),
	schema.FieldOf("id", schema.UUID(),
		func(value Item) string { return value.ID },
		func(value *Item, field string) { value.ID = field }),
	schema.FieldOf("tags", schema.MinItems(schema.List(schema.Text()), 1),
		func(value Item) []string { return value.Tags },
		func(value *Item, field []string) { value.Tags = field }),
	schema.OptionalFieldOf("note", schema.MaxLength(schema.Text(), 200),
		func(value Item) (string, bool) {
			var absent string
			if value.Note == nil {
				return absent, false
			}
			return *value.Note, true
		},
		func(value *Item, field string) { value.Note = &field }),
)

// Movement is generated from its description.
type Movement interface{ isMovement() }

// MovementSchema describes Movement. It is generated from its description.
var MovementSchema = schema.OneOf[Movement]("Movement",
	schema.DocumentedVariant("stock arriving",
		schema.VariantOf("received", ReceivedSchema,
			func(value Movement) (Received, bool) { held, is := value.(Received); return held, is },
			func(held Received) Movement { return held })),
	schema.DocumentedVariant("stock leaving",
		schema.VariantOf("shipped", ShippedSchema,
			func(value Movement) (Shipped, bool) { held, is := value.(Shipped); return held, is },
			func(held Shipped) Movement { return held })),
)

// Received is generated from its description.
type Received struct {
	Count uint16 `json:"count"`
}

func (Received) isMovement() {}

// ReceivedSchema describes Received. It is generated from its description.
var ReceivedSchema = schema.Struct[Received]("Received",
	schema.FieldOf("count", schema.Uint16(),
		func(value Received) uint16 { return value.Count },
		func(value *Received, field uint16) { value.Count = field }),
)

// Shipped is generated from its description.
type Shipped struct {
	Count uint16 `json:"count"`
	To    string `json:"to"`
}

func (Shipped) isMovement() {}

// ShippedSchema describes Shipped. It is generated from its description.
var ShippedSchema = schema.Struct[Shipped]("Shipped",
	schema.FieldOf("count", schema.Uint16(),
		func(value Shipped) uint16 { return value.Count },
		func(value *Shipped, field uint16) { value.Count = field }),
	schema.FieldOf("to", schema.Hostname(),
		func(value Shipped) string { return value.To },
		func(value *Shipped, field string) { value.To = field }),
)
